// OTP model interface

export interface Otp {
  id?: number;          // Optional: generated by DB
  email: string;        // Email to which OTP is sent
  otp: string;          // 6-digit OTP code
  expires_at: Date;     // Expiration timestamp
  created_at?: Date;    // Optional: created timestamp
}
