// backend/src/models/User.ts

// User model interface
export interface User {
  id?: number;           // Auto-generated by the database
  name?: string;         // User name (optional for now)
  email: string;         // User email
  password?: string;     // Hashed password (optional if not needed in some contexts)
  phone?: string | null; // Optional phone number
  avatar?: string | null;// Optional avatar URL
  role?: 'user' | 'admin' | 'driver'; // Optional role
  created_at?: Date;     // Optional timestamp when the user was created
}
